docs: fix broken links about benchmarking builtin gadgets
The broken link was as follows:
```
ERROR: 1 dead links found in ./docs/devel/ci.md !
[✖] https://github.com/inspektor-gadget/inspektor-gadget/blob/main/internal/benchmarks/benchmarks_test.go → Status: 404
```

Fixes: 0a0d86a3720a ("benchmarks: Remove built-in gadgets benchmarks")

Signed-off-by: Alban Crequy <alban.crequy@gmail.com>