pkg/gadgets: Adapt capable CO-RE to our needs.
We need to replace gid_t and uid_t by __u32 to avoid compile time errors like:
././bpf/capable.h:14:2: error: unknown type name 'gid_t'
   14 |  gid_t tgid;

We removed everything about stack trace as it ended with the following
error:
map stackmap: map create without BTF: invalid argument

We also removed the test on kernel version as we cannot use __kconfig with
cilium/ebpf.
This test will be done in golang based on LinuxVersionCode().

Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>