docs: fix broken links in image based gadget design docs
The broken link was as follows:
```
ERROR: 2 dead links found in ./docs/design/002-containerized-gadgets.md !
[✖] #socketfilter-programs → Status: 404
[✖] #inspektor-gadget-api → Status: 404
```

Fixes: fb0115c86df5 ("design: Add containerized gadgets design doc")

Signed-off-by: Alban Crequy <alban.crequy@gmail.com>