Makefile.btfgen: skip BPF objects without .BTF.ext
BPF objects contain a .BTF.ext section if they contain BPF programs. But
graphmap_bpfel.o only contains a BPF map without any BPF program. This
cause the following problem:

Error: failed to parse BPF object 'pkg/gadgets/network-graph/tracer/graphmap_bpfel.o': section .BTF.ext not found

This patch skips graphmap_bpfel.o.