signature-verifier: Fix test
Use t.TempDir() instead of os.TempDir() to avoid the same folder being
reused by multiple tests. It was causing the test to fail with:

```
signature-verifier_test.go:127:
    	Error Trace:	/home/runner/work/inspektor-gadget/inspektor-gadget/pkg/signature-verifier/signature-verifier_test.go:127
    	Error:      	Received unexpected error:
    	            	invalid OCI Image Layout: failed to decode OCI layout file: EOF
    	Test:       	TestVerify/no_public_key
```

Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>