image-build: fix update-metadata with targ_comm
gadgets/Makefile suggests to use GADGET_BUILD_PARAMS="--update-metadata"

But that build parameter does not work anymore:
Error: updating metadata file: populating metadata: handling params: "targ_comm" is not const

This is because the targ_comm is not a constant but an array of
constants:
const volatile gadget_comm targ_comm[TASK_COMM_LEN] = {};

This patch updates the code to accept arrays of constants.

Signed-off-by: Alban Crequy <alban.crequy@gmail.com>