Update bcc base container image
Linux 4.5+ introduced asm_inline:
https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d

This introduced this compilation problem:

[E2] In file included from /virtual/main.c:2:
[E2] In file included from include/uapi/linux/ptrace.h:142:
[E2] In file included from ./arch/x86/include/asm/ptrace.h:5:
[E2] ./arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
[E2]         alternative_io ("lsl %[seg],%[p]",
[E2]         ^
[E2] ./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
[E2]         asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
[E2]         ^
[E2] include/linux/compiler_types.h:210:24: note: expanded from macro 'asm_inline'
[E2] #define asm_inline asm __inline
[E2]                        ^

We need this commit of bcc to fix it:
https://github.com/iovisor/bcc/commit/6c853f636178f4526a0885477379424449312b27

Unfortunately, https://hub.docker.com/r/zlim/bcc/tags does not seem to
have new builds for 10 months. So this patch builds a new bcc image with
the fix.