btfgen: ignore bpf iterators
btfgen fails with the following error:
```
  BTFGEN   4.14.214-118.339.amzn1.x86_64.btf
libbpf: prog 'iter/task_file': relo #14: relocation decision ambiguity: success 23824 != success 11867
libbpf: prog 'iter/task_file': relo #14: relocation decision ambiguity: success 24077 != success 12064
Error: error recording relocations for pkg/gadgets/snapshot/file/tracer/iterfile_bpfel.o: Protocol error
Error: error recording relocations for pkg/gadgets/snapshot/file/tracer/iterfile_bpfel.o: Protocol error
```

But btfgen is unnecessary on this bpf program because it requires a
recent Linux kernel with BTF anyway.

Signed-off-by: Alban Crequy <albancrequy@linux.microsoft.com>