include: Split mntns_gadget/mntns_filter.h to avoid error when running gadget
It's possible that a gadget wants to provide the mount namespace but
doesn't want to filter by it. Including gadget/mntns_filter.h was causing
issues on those cases as the gadget_filter_by_mntns constant wasn't never
used:

Error: running gadget: running gadget: install tracer: rewriting constants: rewrite constants: some constants are missing from .rodata: gadget_filter_by_mntns

This is caused because gadget/mntns_filter.h includes a gadget_filter_by_mntns
const, but if gadget_should_discard_mntns_id() is never called, the const
is optmized out by the compiler.

This commit splits that file, introducing gadget/mntns.h to be used
in that case.

Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>