registry: Make mandatory parameters required cmd flags
Before:

```
$ ./kubectl-gadget script
NODE                               OUTPUT
Error: running gadget: rpc error: code = Unknown desc = setting gadget parameters: expected value for "program"
```

^^^ validation was performed in the server side

Now:

```
$ ./kubectl-gadget script
Error: required flag(s) "program" not set
```

Validation is done by cobra on the client side.