docs: fix broken links about grpc api
The broken link was as follows:
```
ERROR: 1 dead links found in ./docs/api/grpc.md !
[✖] https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgettracermanager/api/gadgettracermanager.proto → Status: 404
```

Fixes: 3e9f17e9d010 ("gadget-container: Use KubeManager for hook API and container+tracer collections")

Signed-off-by: Alban Crequy <alban.crequy@gmail.com>